spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  profiles:
    active: native

security:
  user:
    password: password

server:
  port: 8888
