version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    restart: "no"
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"
#  redis-commander:
#    container_name: redis-commander
#    hostname: redis-commander
#    image: rediscommander/redis-commander:latest
#    build: .
#    restart: "no"
#    environment:
#    - REDIS_HOSTS=local:redis:6379
#    ports:
#    - 8081:8081