version: '3'
services:
  db:
    container_name: postgis
    image: mdillon/postgis
    environment:
    - POSTGRES_PASSWORD=root
    - POSTGRES_USER=root
    - POSTGRES_DB=trackdb
    ports:
    - 5432:5432