server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    metadata-map:
      user:
        name: actuator
        password: password
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

security:
  oauth2:
    client:
      clientId: server
      clientSecret: secret
      accessTokenUri: ${ACCESS_TOKEN_URI:http://localhost:5000/oauth/token}
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: ${USER_INFO_URI:http://localhost:5000/uaa/user}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${DB_URI:jdbc:mysql://localhost:3307/statistics}
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  cloud:
    stream:
      bindings:
        trackSaveChannel:
          destination: track.save
          group: trackGroup
        trackStatsChannel:
          destination: stats.track
          contentType: application/json
          group: statsGroup
      default:
          contentType: application/json

